version: "3.8"

services:
  web:
    image: nginx:alpine
    container_name: kerst_teller
    ports:
      - "8009:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./sounds:/usr/share/nginx/html/sounds:ro
